language: minimal

branches:
  only:
    - /.*/

jobs:
  fast_finish: true
  include:
    - name: "Validation"
      os: linux

git:
  depth: 1
  quiet: false

install: skip

script:
  - echo "Running validation..."
  - echo "Success!"

notifications:
  email:
    recipients:
      - ${NOTIFICATION_EMAIL}
    on_success: always
    on_failure: always

cache:
  apt: true
